name: feature work flow 
on:
  push:
    branches-ignore:
      - main # this will ignore this branch
jobs:
  feature-workflow:
    uses: pandalapadu/workflows/.github/workflows/nodejsEKSfeature.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'   